import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  learningSidebar: [
    { type: "autogenerated", dirName: "." },
  ],
}

export default sidebars
